[config]

[templates.base]
input_path = './templates/_base.conf'
output_path = './_base.conf'

[templates.hyprland]
input_path = './templates/hyprland.conf'
output_path = '~/.config/hypr/matugen/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all matugen"

# [templates.qt5ct]
# input_path = './templates/qtct.conf'
# output_path = '~/.config/qt5ct/colors/matugen.conf'
#
# [templates.qt6ct]
# input_path = './templates/qtct.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'
#
# [templates.gtk3]
# input_path = './templates/gtk.css'
# output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface color-scheme prefer-{{mode}}'
#
# [templates.gtk4]
# input_path = './templates/gtk.css'
# output_path = '~/.config/gtk-4.0/colors.css'

[templates.vesktop]
input_path = './templates/vesktop.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.neovim]
input_path = './templates/neovim.lua'
output_path = '~/.config/nvim/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -SIGHUP btop'

[templates.millennium]
input_path = './templates/steam.css'
output_path = '~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css'
