[mgr] # ────────────────────────────────────────────────────────────────────────────────────────
  ratio = [0,2,6]
  show_hidden = true
  show_symlink = false
  scrolloff = 200
[[plugin.prepend_fetchers]] # ──────────────────────────────────────────────────────────────────
  id   = "git"
  name = "*"
  run  = "git"
[[plugin.prepend_fetchers]] # ──────────────────────────────────────────────────────────────────
  id   = "git"
  name = "*/"
  run  = "git"
# ──────────────────────────────────────────────────────────────────────────────────────────────
